version: "3.9"

services:
  cvproject:
    container_name: cvproject_web_container
    build: .
    volumes:
      - ./:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db-postgres
    env_file:
      - .env

  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data
