version: "3.9"

services:
  web:
    container_name: cvproject_web_container
    build: .
    command: ["web"]
    volumes:
      - ./:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db-postgres
      - redis
    env_file:
      - .env

  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

  celery_worker:
    container_name: cvproject_celery_worker
    build: .
    command: ["celery_worker"]
    volumes:
      - ./:/app
    depends_on:
      - db-postgres
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
    name: postgres_data
